export const tournamentNamesByPlatform: Record<string, string[]> = {
  "Poker Stars": [
    "Big",
    "Bounty Builder",
    "Hot",
    "Hot Hyper",
    "Hot KO",
    "Hyper KO",
    "Micro Bounty Builder HR",
    "Mini Mystery Express",
    "Sunday Storm",
  ],
  GG: [
    "Bounty Hunters",
    "Bounty Hunters Big Game",
    "Bounty Hunters Deepstack Turbo",
    "Bounty Hunters Hyper Special",
    "Bounty Hunters Mini Big Game",
    "Bounty Hunters Special",
    "Bounty King Jr",
    "Daily Classic",
    "Daily Hyper",
    "Daily Hypersonic",
    "Daily Special",
    "Daily Turbo",
    "Fifty Stack",
    "GGMasters Classic",
    "Mini Forty Stack",
    "Mini Heater",
    "Mini Hypersonic",
    "Mini LUCKY SEVENS Superstack Turbo",
    "Mini Saver",
    "Mini SUPER SIX Bounty Turbo",
    "Speed Racer Bounty",
    "Zodiac Deepstack Turbo",
  ],
  WPT: [
    "Bounty Brawl",
    "Bounty Brawl Mini Encore",
    "Bounty Brawl Mini Main Event",
    "Bounty Hunters 30 Grand",
    "Bounty King Baby - PKO",
    "Bounty King Jr - PKO",
    "Bounty Light Weight Championship",
    "Daily Crown Baby Closer",
    "Daily Crown Deep Thrill",
    "Daily Crown MAIN EVENT",
    "Hyper Dash",
    "Mini Mystery Slam",
    "One Shot Freezout",
    "One Shot Freezout Doublestack",
    "Rocket Dash",
    "Super Sonic Hyper Dash",
  ],
  "Party Poker": [
    "8-MAX Turbo",
    "8-Max Deepstack",
    "Bounty Battle Hyper",
    "Bounty Hunter",
    "Bounty Hunter Hyper",
    "Bounty Hunter Turbo",
    "Daily Legends",
    "Daily Legends Clássico",
    "Daily Legends Deepstack",
    "Daily Legends Gladiator",
    "The Super",
  ],
  Champions: [
    "Big Deuce KO",
    "Bounty Hunter",
    "Fists of Fury-Rebuy",
    "Friday Mystery",
    "Late Bounty XL Mini",
    "Mystery",
    "Mystery Finisher",
    "Mystery Hyper",
    "Night Bounty XL",
    "Progressive Knockout",
    "Super Secret",
    "SUNSET ELIMINATOR",
  ],
  "888": [
    "Deepstack",
    "Early Mystery Bounty",
    "Early PKO Rumble",
    "Early Turbo",
    "Micro Rollers - Big Shot",
    "Micro Rollers - Mystery Bounty",
    "Micro Rollers - Mystery Bounty Turbo",
    "Mystery Bounty",
    "Mystery Bounty Turbo",
    "PKO 6-Max",
    "PKO Rumble",
    "PKO Turbo",
    "Super Knockout",
    "Turbo 6-Max",
    "Voyage",
  ],
};
